---
iptables_allow_icmp_inbound:
  - ANY
iptables_allow_https_inbound:
  - ANY  # Port 443 is used as fallback for SSH on jumphosts. Port 443 outbound is allowed by default.
iptables_allow_ssh_inbound:
  - ANY
iptables_allow_ssh_outbound:
  - ANY
ssh_host_signer_hostnames: "{{ inventory_hostname }}\
    {% for network_id in ip_addresses[inventory_hostname] %}\
      {% if ip_addresses[inventory_hostname][network_id]['fqdn'] is defined and
            ip_addresses[inventory_hostname][network_id]['fqdn'] | length >= 1 %}\
        {% if ip_addresses[inventory_hostname][network_id]['fqdn'] == 'NXDOMAIN' %}\
          ,{{ ip_addresses[inventory_hostname][network_id]['address'] }}\
        {% else %}\
          ,{{ ip_addresses[inventory_hostname][network_id]['fqdn'] }}\
        {% endif %}\
      {% endif %}\
    {% endfor %}"
# This is enforcing that jumphosts use `yum_repos` for defining repositories,
# since jumphosts cannot use Pulp
repo_manager: 'none'
user_quota_on_root_partition:
  blocks_soft: 512K
  blocks_hard: 1024K
  inodes_soft: 8k
  inodes_hard: 10k
#
# Configure limited subset of repos for jumphosts.
# Listing the repo ID here does not mean the repo will be enabled!
# It means the repo config as listed in the yum_repos variable from
#     group_vars/all/repos.yml
# will be applied to the machine, which can include instructions for both enabling or disabling a repo.
#
managed_yum_repos:
  rocky9:
    - baseos
    - baseos-debug
    - baseos-source
    - appstream
    - appstream-debug
    - appstream-source
    - crb
    - crb-debug
    - crb-source
    - rocky-release-security
    - epel
    - epel-debuginfo
    - epel-source
    - rsyslog
...
