---
#
# Firewall configuration.
#
iptables_allow_icmp_inbound:
  - "{{ all.ip_addresses['umcg']['net1'] }}"
  - "{{ all.ip_addresses['umcg']['internal1'] }}"
  - "{{ all.ip_addresses['umcg']['basiswerkplek'] }}"
  - "{{ all.ip_addresses['umcg']['win10vdi'] }}"
  - "{{ all.ip_addresses['umcg']['net4'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan1337'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"

iptables_allow_ssh_inbound:
  - "{{ all.ip_addresses['umcg']['net1'] }}"
  - "{{ all.ip_addresses['umcg']['internal1'] }}"
  - "{{ all.ip_addresses['umcg']['basiswerkplek'] }}"
  - "{{ all.ip_addresses['umcg']['win10vdi'] }}"
  - "{{ all.ip_addresses['umcg']['net4'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan1337'] }}"
  - "{{ talos_cluster.ip_addresses['reception']['vlan16'] }}"
