---
- name: Make local mountpoint
  file:
    path: "/apps"
    mode: 0777
    state: directory

- name: "check mount point /apps"
  command: mountpoint /apps
  register: mount_local
  failed_when: false

- name: Create an ext4 filesystem on /dev/vdb
  filesystem:
    fstype: ext4
    dev: /dev/vdb
  when:
    mount_local.rc == 1

- name: Mount /dev/vdb on /apps
  mount:
    path: /apps
    src: /dev/vdb
    fstype: ext4
    opts: rw,relatime
    state: present

- name: mount all mountpoints in fstab
  command: mount -a
  args:
    warn: false
  when:
    mount_local.rc == 1
