---
- name: Make scratch mountpoint
  file:
    path: "/scratch"
    mode: 0777
    state: directory

- name: "check mount point /scratch"
  command: mountpoint /scratch
  register: mount_scratch
  failed_when: false

- name: Create an ext4 filesystem on /dev/vdb
  filesystem:
    fstype: ext4
    dev: /dev/vdb
  when:
    mount_scratch.rc == 1

- name: Mount /dev/vdb on /scratch
  mount:
    path: /scratch
    src: /dev/vdb
    fstype: ext4
    opts: rw,relatime
    state: present

- name: mount all mountpoints in fstab
  command: mount -a
  args:
    warn: false
  when:
    mount_scratch.rc == 1
