---
- name: Running logs_client role.
  hosts:
    # TODO - we should probably just set it to 'all'
    - jumphost
    - cluster
    - chaperone,!mit_chaperone
    - repo
    - logs
  roles:
    - role: logs_client
      when: ((syslog_external_servers is defined and ( syslog_external_servers|length>0 )) or ( cluster_class is defined ))
            and ( ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] > "7" )
...
