---
- name: 'Install monitoring tools.'
  hosts: sys_admin_interface
  roles:
    - prom_server
    - grafana
    - cadvisor

- name: 'Monitoring of the hardware components.'
  hosts: metal
  tasks:
  roles:
    - cadvisor
    - node_exporter
    - ipmi_exporter

- name: 'Monitoring of the virtualized components.'
  hosts: jumphost, cluster
  tasks:
  roles:
    - node_exporter

- name: 'Monitoring of the SLURM resource manager.'
  hosts: user_interface
  roles:
    - slurm_exporter

- name: 'Jumphost proxies Prometheus for Grafana in the cloud.'
  hosts: jumphost
  tasks:
  roles:
    - grafana_proxy
...