---
- name: Dummy to gather facts
  hosts: sys_admin_interface
  tasks: []

- name: Install virtual compute nodes
  hosts: compute_vm
  tasks:
  roles:
    - slurm_client

- name: Install user interface
  hosts: user_interface
  tasks:
  roles:
    - slurm_client
...