---
- name: Deploy ssh_host_signer role on jumphosts.
  hosts: jumphost
  roles:
    - ssh_host_signer

- name: Deploy ssh_host_signer role on machines behind jumphosts.
  hosts: all,!jumphost,!openstack_api,!mit_chaperone
  roles:
    - ssh_host_signer
...
