---
- name: Install sssd role.
  hosts:
    - jumphost
    - cluster
    - chaperone,!mit_chaperone
    - data_transfer
  strategy: linear
  roles:
    - role: sssd
      when: use_sssd | default(false) | bool
    - role: sshd  # Always re-run sshd role after potentially changing the logic to fetch public keys.
      when: use_sssd | default(false) | bool
...
