---
- hosts:
    - jumphost
  roles:
    - static_hostname_lookup

- hosts:
    - chaperone
    - cluster
    - data_transfer
    - irods
    - ldap_server
    - logs
    - repo
  roles:
    - static_hostname_lookup
...
