---
- name: Install service files.
  template:
    src: "templates/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items:
    - openldap.service
    - phpldapadmin.service
  become: true

- name: Make directory for the openldap ldif volume.
  file:
    path: "/srv/openldap/custom"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install ldif files for overlays.
  copy:
    src: "files/{{ item }}"
    dest: "/srv/openldap/custom/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 01-overlay-memberof
  become: true

- name: Make sure services are started.
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - openldap.service
    - phpldapadmin.service
  become: true
...
