# Create local admin groups & users and allow admin group to use sudo on all hosts.
---
- name: Set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
  become: true
- name: Create admin groups for local admin users.
  group:
    name: "{{ item }}"
    gid: "{{ auth_groups[item].gid }}"
    state: present
  with_items: "{{ local_admin_groups }}"
  become: true
- name: 'Allow passwordless sudo for local admin users.'
  lineinfile:
    path: '/etc/sudoers'
    line: "%admin  ALL=(ALL:ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  become: true
- name: "Create private groups for user's home dirs."
  group:
    name: "{{ item }}"                 # Use same name as user's account name for user's private group.
    gid: "{{ auth_users[item].uid }}"  # Use same GID as user's UID for user's private group.
    state: present
  with_items: "{{ local_admin_users }}"
  become: true
- name: 'Create /admin root dir for the home dirs of local admin users.'
  file:
    path: '/admin'
    owner: root
    group: root
    mode: '0755'
    state: directory
  become: true
- name: Create local admin users and append them to relevant groups.
  user:
    name: "{{ item }}"
    uid: "{{ auth_users[item].uid }}"
    comment: "{{ auth_users[item].comment }}"
    group: admin
    groups: "{{ local_admin_groups }}"
    home: "/admin/{{ item }}"
    append: false
  with_items: "{{ local_admin_users }}"
  become: true
- name: 'Deploy authorized keys for admins.'
  authorized_key:
    user: "{{ item }}"
    key: "{{ auth_users[item].pub_keys }}"
    state: present
    exclusive: true
  with_items: "{{ local_admin_users }}"
  become: true
...
