---
- name: Create security groups.
  ansible.builtin.include_tasks:
    file: security_groups.yml

- name: Create networks and subnets.
  ansible.builtin.include_tasks:
    file: networks.yml
  loop: "{{ azure_networks
            | rejectattr('create', 'undefined')
            | selectattr('create', 'equalto', true)}}"
  loop_control:
    loop_var: network
...
