---
- name: "Create {{ network['name'] }} network."
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ network['name'] }}"
    location: "{{ azure_location }}"
    address_prefixes_cidr:
      - "{{ network['cidr'] }}"
    dns_servers: "{{ nameservers | list }}"
    resource_group: "{{ azure_resource_group }}"

- name: "Create {{ network['name'] }}_subnet in {{ network['name'] }} network."
  azure.azcollection.azure_rm_subnet:
    name: "{{ network['name'] }}_subnet"
    virtual_network: "{{ network['name'] }}"
    state: "present"
    security_group: "{{ stack_prefix }}_open"
    address_prefix: "{{ network['cidr'] }}"
    resource_group: "{{ azure_resource_group }}"
  register: subnet_result
...
