---
oxfordnanoportal_repo_url: https://cdn.oxfordnanoportal.com/apt/ont-repo.pub
generic_deps:
  - curl
  - git
  - wget
  - nano
  - rsync
  - openssh-server

#only for testing
minknow_backup_install: false
...