---
# device defaults
network_device_file_prefix: 'ifcfg-'
#
# https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
# Do not set a default yet as that may break older machines.
#
#enable_predictable_network_interface_names: true
