---
- name: Install BeeGFS server services
  ansible.builtin.package:
    state: latest
    update_cache: true
    name: "{{ item }}"
  loop: "{{ beegfs_install_services }}"
  become: true

- name: Configure BeeGFS management service
  ansible.builtin.lineinfile:
    path: /etc/beegfs/beegfs-mgmtd.conf
    regexp: '^storeMgmtdDirectory\s*='
    line: "storeMgmtdDirectory={{ beegfs_storage_dir }}/mgmtd"
  notify:
    - systemd_reload
    - restart-beegfs-mgmtd
  become: true

- name: Configure BeeGFS metadata service
  ansible.builtin.lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - { regex: '^storeMetaDirectory\s*=', line: "storeMetaDirectory={{ beegfs_storage_dir }}/meta" }
    - { regex: '^sysMgmtdHost\s=', line: "sysMgmtdHost={{ inventory_hostname }}" }
  notify:
    - systemd_reload
    - restart-beegfs-meta
  become: true

- name: Configure Storage directory on BeeGFS storage service
  ansible.builtin.lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: '^storeStorageDirectory\s*='
    line: "storeStorageDirectory={{ beegfs_storage_dir }}/storage"
  notify:
    - systemd_reload
    - restart-beegfs-storage
  become: true

- name: Configure Caching directory on BeeGFS storage service
  ansible.builtin.lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: '^storeCacheDirectory\s*='
    line: "storeCacheDirectory=/mnt/beegfs-cache"
  notify:
    - systemd_reload
    - restart-beegfs-storage
  become: true

- name: Configure connAuthFile
  ansible.builtin.copy:
    content: "{{ beegfs_connAuthFile_content }}"
    dest: /etc/beegfs/connauthfile
    owner: root
    group: root
    mode: '0400'
  notify:
    - systemd_reload
    - restart-beegfs-mgmtd
    - restart-beegfs-meta
    - restart-beegfs-storage
  become: true

- name: Configure all the services to use the connAuthFile
  ansible.builtin.lineinfile:
    path: "/etc/beegfs/{{ item }}"
    regexp: '^connAuthFile\s*='
    line: "connAuthFile=/etc/beegfs/connauthfile"
  with_items:
    - beegfs-mgmtd.conf
    - beegfs-meta.conf
    - beegfs-storage.conf
  notify:
    - systemd_reload
    - restart-beegfs-mgmtd
  become: true
...
