---
- name: 'Create folder for "{{ ldap_domain }}" LDAP database.'
  ansible.builtin.file:
    path: "/usr/local/openldap/var/{{ ldap_domain }}-data"
    state: directory
    mode: '0750'
    owner: ldap
    group: ldap
  become: true

- name: "Query OpenLDAP config database and search for {{ ldap_domains[ldap_domain]['base'] }} olcDatabase"
  community.general.ldap_search:
    server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
    scope: children
    dn: cn=config
    filter: "(olcSuffix={{ ldap_domains[ldap_domain]['base'] }})"
    attrs:
      - olcDatabase
  register: mdb_of_current_domain
  become: true

- name: 'Query OpenLDAP config database for list of all existing databases.'
  community.general.ldap_search:
    server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
    scope: onelevel
    dn: cn=config
    filter: "(objectClass=olcDatabaseConfig)"
    attrs:
      - olcDatabase
  register: existing_databases_query
  become: true

- name: 'Configure OpenLDAP databases'
  become: true
  vars:
    existing_databases: "{{ existing_databases_query['results']
        | selectattr('olcDatabase', 'defined')
        | map(attribute='olcDatabase') }}"
    use_database_index: "{{ existing_databases
        | regex_replace('{\\[([1-9][0-9]*)\\]}', '\\1')
        | map('int')
        | sort
        | last + 1
        if mdb_of_current_domain.results
          | selectattr('olcDatabase', 'defined')
          | list | length == 0
        else
          mdb_of_current_domain.results
          | selectattr('olcDatabase', 'defined')
          | map(attribute='olcDatabase')
          | join('')
          | regex_replace('{([1-9][0-9]*)}.*', '\\1')
        }}"
    use_database_index_brackets: "{% raw %}{{% endraw %}{{ use_database_index }}{% raw %}}{% endraw %}"
  block:
    - name: 'Debug the indexes'
      ansible.builtin.debug:
        msg:
          - "ldap_server_existing_databases: {{ existing_databases }}"
          - "ldap_server_use_database_index: {{ use_database_index }}"
    - name: 'Create database for "{{ ldap_domain }}" domain in the OpenLDAP config database {{ use_database_index_brackets }}.'
      community.general.ldap_entry:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "olcDatabase={{ use_database_index_brackets }}mdb,cn=config"
        state: present
        objectClass:
          - olcDatabaseConfig
          - olcMdbConfig
        attributes:
          #
          # These attributes cannot be changed with this role.
          #
          olcDatabase: "{{ use_database_index_brackets }}mdb"
          olcDbDirectory: "/usr/local/openldap/var/{{ ldap_domain }}-data"
          olcSuffix: "{{ ldap_domains[ldap_domain]['base'] }}"
      when: mdb_of_current_domain.results | selectattr('olcDatabase', 'defined') | list | length == 0

    - name: 'Update "{{ ldap_domain }}" database attributes in the OpenLDAP config database.'
      community.general.ldap_attrs:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "olcDatabase={{ use_database_index_brackets }}mdb,cn=config"
        state: exact
        attributes:
          olcDbMode: '0600'
          olcDbMaxSize: 104857600
          olcRootDN: "cn=manager,{{ ldap_domains[ldap_domain]['base'] }}"
          olcRootPW: "{{ openldap_root_hash }}"
          olcLimits: '{0}users size=unlimited time=unlimited'
          olcMonitoring: 'TRUE'
          olcDbNoSync: 'FALSE'
          olcDbIndex:
            - objectClass eq
            - cn,givenName,sn,mail pres,eq,sub
            - uid pres,eq
            - member eq

    - name: 'Update OpenLDAP config database to create memberOf overlay for dynamic memberOf attributes in "{{ ldap_domain }}" database.'
      community.general.ldap_entry:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "olcDatabase={{ use_database_index_brackets }}mdb,cn=config"
        state: present
        objectClass:
          - olcOverlayConfig
          - olcMemberOf
        attributes:
          #
          # These attributes cannot be changed with this role.
          #
          olcOverlay: '{0}memberof'
          #
          # These attributes can be changed.
          #
          olcMemberOfRefInt: 'TRUE'
          olcMemberOfGroupOC: groupOfMembers
          olcMemberOfMemberAD: member
          olcMemberOfMemberOfAD: memberOf

    - name: 'Update "{{ ldap_domain }}" database ACLs in the OpenLDAP config database.'
      community.general.ldap_attrs:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "olcDatabase={{ use_database_index_brackets }}mdb,cn=config"
        state: exact
        ordered: true
        attributes:
          olcAccess:
            - to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break
            - to attrs=userPassword by anonymous auth by * none
            - to dn.subtree="{{ ldap_domains[ldap_domain]['base'] }}"
              by dn="{{ ldap_credentials[ldap_domain]['admin']['dn'] }}" write
              by dn="{{ ldap_credentials[ldap_domain]['readonly']['dn'] }}" read
              by * none

    - name: 'Create top level entry in "{{ ldap_domain }}" LDAP database.'
      community.general.ldap_entry:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "{{ ldap_domains[ldap_domain]['base'] }}"
        state: present
        objectClass:
          - domain

    - name: 'Create functional accounts to access the "{{ ldap_domain }}" LDAP database.'
      community.general.ldap_entry:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "{{ ldap_credentials[ldap_domain][item]['dn'] }}"
        state: present
        objectClass:
          - simpleSecurityObject
          - organizationalRole
        attributes:
          #
          # These attributes cannot be changed with this role.
          #
          cn: "{{ ldap_credentials[ldap_domain][item]['dn'] | regex_replace('^cn=([^,]+),.*', '\\1') }}"
          #
          # These mandatory attributes will be updated if necessary with the ldap_attrs task below.
          #
          userPassword: "{{ ldap_credentials[ldap_domain][item]['hash'] }}"
      loop: "{{ ldap_functional_accounts | flatten(levels=1) }}"

    - name: 'Update attributes of functional accounts used to access the "{{ ldap_domain }}" LDAP database.'
      community.general.ldap_attrs:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "{{ ldap_credentials[ldap_domain][item]['dn'] }}"
        state: exact
        attributes:
          userPassword: "{{ ldap_credentials[ldap_domain][item]['hash'] }}"
          description: "LDAP {{ item }} user for {{ ldap_domains[ldap_domain]['base'] }}."
      loop: "{{ ldap_functional_accounts | flatten(levels=1) }}"

    - name: 'Configure replication provider for "{{ ldap_domain }}" database.'
      community.general.ldap_attrs:
        server_uri: "ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi"
        dn: "olcDatabase={{ use_database_index_brackets }}mdb,cn=config"
        state: exact
        ordered: true
        attributes:
          olcSyncrepl:
            - rid=001
              provider="{{ ldap_domains[ldap_domain]['replication_provider_uri'] }}/"
              searchbase="{{ ldap_domains[ldap_domain]['replication_provider_base'] }}"
              type=refreshAndPersist
              bindmethod=simple
              binddn="{{ ldap_credentials[ldap_domain]['replication_provider']['dn'] }}"
              credentials="{{ ldap_credentials[ldap_domain]['replication_provider']['pw'] }}"
              retry="60 +"
              timeout=30
              network-timeout=5
              tls_cacert="/etc/pki/tls/certs/ca-bundle.trust.crt"
      when:
        - ldap_domains[ldap_domain]['replication_provider_uri'] is defined and ldap_domains[ldap_domain]['replication_provider_uri'] | length >= 1
        - ldap_domains[ldap_domain]['replication_provider_base'] is defined and ldap_domains[ldap_domain]['replication_provider_base'] | length >= 1
...
