---
- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  listen: systemd_reload

- name: Restart beegfs-mgmtd
  ansible.builtin.systemd:
    name: beegfs-mgmtd
    enabled: true
    state: restarted
  listen: restart-beegfs-mgmtd
  become: true

- name: Restart beegfs-meta
  ansible.builtin.systemd:
    name: beegfs-meta
    enabled: true
    state: restarted
  listen: restart-beegfs-meta
  become: true

- name: Restart beegfs-storage
  ansible.builtin.systemd:
    name: beegfs-storage
    enabled: true
    state: restarted
  listen: restart-beegfs-storage
  become: true
...
