---
- name: Install roles needed for all virtual cluster components.
  hosts: cluster
  become: true
  tasks:
  roles:
      # - spacewalk_client
   - ldap
     #- cluster

     #- import_playbook: users.yml
