---
# This playbook will reset the instalation to facilitate a new installation.
# All data is lost!
- hosts: metal
  become: True
  name: Dummy to gather facts
  tasks:
    - name: Stop docker service
      shell: "systemctl stop docker"
    - name: Verify docker is stopped.
      systemd:
        name: docker
        state: stopped
    - name: remove volumes
      shell: "rm -rf /srv"

- hosts: cinder-storage
  gather_facts: false
  become: True
  tasks:
    - name: wipe cinder storage.
      shell: "dd if=/dev/zero of={{ storage_volume }} bs=1M count=1 && sync"

- hosts: nova-compute
  gather_facts: false
  become: True
  tasks:
    - name: kill all vm's
      shell: "for machine in  $(virsh list --uuid ); do virsh destroy $machine ; done"
    - name: wipe all vm's
      shell: "for machine in  $(virsh list --uuid --all); do virsh undefine $machine ; done"
