---
- src: hrisgavin.ansible-ssh-host-signer
# pull down common roles from the HPC cloud repo
- src: ssh://git@git.webhosting.rug.nl:222/HPC/hpc-cloud.git
  name: hpc-cloud
  version: umcg-0.1
  scm: git

# Mostly user accounts of hpc playbooks.
- src: ssh://git@git.webhosting.rug.nl:222/HPC/HPCplaybooks.git
  name: HPCplaybooks
  version: master
  scm: git

  # From galaxy
#
- src: geerlingguy.firewall

# 
- src: chrisgavin.ansible-ssh-host-signer
