#
# Install cvmfs_client.
#
---
- name: 'Check OS version of target host.'
  ansible.builtin.fail:
    msg: 'This role requires RedHat/CentOS version >= 9.x'
  when: ansible_facts['os_family'] != "RedHat" or ansible_facts['distribution_major_version'] < "9"

- name: 'Set selinux in permissive mode.'
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true

- name: 'Ensure CVMFS repo is installed.'
  ansible.builtin.get_url:
    url: "{{ cvmfs_repo_url }}"
    dest: /etc/yum.repos.d/cernvm.repo
  become: true

- name: 'Add CVMFS repo GPG key.'
  ansible.builtin.rpm_key:
    state: present
    key: "{{ cvmfs_repo_key_url }}"
  become: true

- name: 'Install CVMFS client package.'
  ansible.builtin.package:
    name:
      - cvmfs
    state: "{{ cvmfs_package_state }}"
    update_cache: true
  become: true

- name: 'Configure autofs by running setup command to ensure /etc/auto.master.d/cvmfs.autofs exists.'
  ansible.builtin.command:
    cmd: cvmfs_config setup
    creates: /etc/auto.master.d/cvmfs.autofs
  become: true

- name: 'Reload autofs service in order to apply the updated configuration.'
  ansible.builtin.service:
    name: autofs
    state: reloaded
  become: true

- name: 'Add repositories to cvmfs and make sure file exists.'
  ansible.builtin.blockinfile:
    path: /etc/cvmfs/default.local
    block: | 
      CVMFS_REPOSITORIES=hpc.umcg.nl
      CVMFS_HTTP_PROXY=DIRECT
    create: true
  become: true
...
