---
# Install Docker. Centos needs te be added.

- apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: install docker
  apt: pkg={{ item }} state=latest
  with_items:
     - docker-engine
     - python-docker
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: make sure service is started
  systemd:
    name: docker.service
    state: started
