---
# Note, that cluster_part1.yml already calls
#   init.yml
#   pre_deploy_checks.yml
# playbooks, so no need to do it again.

- name: Import cluster_part1.yml
  ansible.builtin.import_playbook: cluster_part1.yml

- name: '###==-> Extra roles for BeeGFS server. <-==###'
  hosts:
    - beegfs_server
  roles:
    - role: perc_cli
      when: perc_devices is defined and perc_devices
    - local_storage
    - beegfs_server
    - beegfs_client

- name: Import cluster_part2.yml
  ansible.builtin.import_playbook: cluster_part2.yml

...
