---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: Import initialization playbook for all hosts.
  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles only for completely managed chaperones <-==###'
  hosts: chaperone,!mit_chaperone
  roles:
    - iptables
    - grub
    - swap
    - logrotate
    - remove
    - update
    - logins
    - role: sssd
      when: use_sssd | default(false) | bool
    - sshd
    - basic_security
    - figlet_motd
    - role: logs_client
      when: logs_class is defined
    - resolver
    - coredumps

- name: '###==-> Roles for all chaperones. <-==###'
  hosts: chaperone
  roles:
    - ssh  # client
    - locale
    - cluster
    - regular_users
    - sudoers
    - role: local_storage
      when: local_mounts is defined and local_mounts | length > 0
    - shared_storage
    - build_environment
    - envsync

- name: '###==-> Roles only for partially managed chaperones <-==###'
  hosts: mit_chaperone
  roles:
    - logs_toprm
    - ogm
...
