#
# This play depends on:
#   * cluster_part1.yml
#   * cluster_part2.yml
#
---
- import_playbook: pre_deploy_checks.yml

- name: '###==-> Extra roles for DAIs. <-==###'
  hosts:
    - deploy_admin_interface
  roles:
    - mount_volume
    - build_environment
    - envsync
...
