---
#- name: Import pre deploy checks.
#  ansible.builtin.import_playbook: pre_deploy_checks.yml

#- name: Import initialization playbook for all hosts.
#  ansible.builtin.import_playbook: init.yml

- name: '###==-> Roles for p2solo server. <-==###'
  hosts:
    - p2solo_server
  roles:
    - firewall
    - ssh
#    - locale needed???
    - logrotate
    - remove
#    - update aanpassen voor Debian/ubuntu
#    - sshd update ?
    - basic_security
#    - p2solo_server
...
