#
# This play depends on:
#   * cluster_part1.yml
#   * cluster_part2.yml
#
---
- import_playbook: pre_deploy_checks.yml

- name: '###==-> Extra roles for SAIs. <-==###'
  hosts:
    - sys_admin_interface
  roles:
    - mount_volume
    - slurm_management
    - prom_server
    - grafana
    - cadvisor
  vars:
    # These variables are needed by the mariadb role.
    # Which is a depencency of the slurm_management role.
    # See roles/slurm/meta/main.yml
    hostname_node0: "{{ ansible_hostname }}"
    ip_node0: "{{ ansible_default_ipv4['address'] }}"
...
