---
azure_resource_group: "{{ stack_name }}"
azure_location: "westeurope"
#
# security_group_names_of_all_hosts_created_in_azure are the hosts specified in the inventory,
# which also have a `azure_flavor` specified, indicating these machines are created in Azure.
#
security_group_names_of_all_hosts_created_in_azure: "{{ hostvars
    | json_query('* | [?azure_flavor] | [].host_networks[].security_group')
    | flatten
    | unique }}"
# network_names_of_all_hosts_created_in_azure: "{{ hostvars
#     | json_query('* | [?azure_flavor] | [].host_networks[].name')
#     | flatten
#     | unique }}"
...
