---
- name: Configure automatic cleanup of old data.
  ansible.builtin.include_tasks:
    file: configure_cleanup.yml
  when: regular_groups
        | default([])
        | selectattr('name', 'equalto', 'umcg-genomescan')
        | list
        | length > 0
...
