---
- name: Install NetworkManager and nmstate.
  package:
    name:
      - NetworkManager
      - nmstate
    state: latest
    update_cache: true
  become: true

- name: Create /etc/systemd/network directory.
  ansible.builtin.file:
    path: /etc/systemd/network
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

#
# Slot-based naming scheme has priority over path-based naming scheme,
# but is not stable: was introduced later and the removed again for virtual network interfaces,
# because it can cause naming conflicts.
#
- name: Deploy /etc/systemd/network/99-default.link for customised udev network device renaming policy ordering.
  ansible.builtin.template:
    src: 99-default.link
    dest: /etc/systemd/network/99-default.link
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true

#
# Remove /etc/udev/rules.d/70-persistent-net.rules to make our new rules apply
# and interfaces are stuck on an old name based on a broken rule.
# File content example with bad slot-based interface names linked tp specific MAC addresses:
#     SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="fa:16:3e:1d:d9:9a", NAME="ens3"
#     SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="fa:16:3e:34:33:d7", NAME="ens4"
#     SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="fa:16:3e:81:c0:bf", NAME="ens5"
#     SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="fa:16:3e:43:01:be", NAME="ens6"
#
- name: Delete /etc/udev/rules.d/70-persistent-net.rules.
  ansible.biultin.file:
    path: /etc/udev/rules.d/70-persistent-net.rules
    state: absent
  become: true

#
# To ensure the custom /etc/systemd/network/99-default.link config is included in the initramfs,
# so it will also be applied during early boot, and that it will be included in future kernel updates,
# we would have to
#    * create
#          /etc/dracut.conf.d/predictable_network_interface_naming.conf
#      with content
#          install_items+=" /etc/systemd/network/99-default.link " # Include custom NamePolicy
#    * and recreate the initramfs with
#          dracut -f /boot/initramfs-$(uname -r).img $(uname -r)
# Unfortunately that does not work as documented due to bugs in udev and/or systemd and/or cloud init.
# Therefore we re-apply our custom NamePolicy from /etc/systemd/network/99-default.link using udev
# later in the boot sequence, but before we using things like shared file systems or NHC,
# that rely on specific network interface names.
#
- name: Deploy /usr/local/sbin/fix_network_interface_names to apply customised udev network device renaming.
  ansible.builtin.template:
    src: fix_network_interface_names.bash
    dest: /usr/local/sbin/fix_network_interface_names
    owner: 'root'
    group: 'root'
    mode: '0750'
  become: true

- name: Deploy fix_network_interface_names.service for systemd.
  ansible.builtin.template:
    src: fix_network_interface_names.service
    dest: /usr/lib/systemd/system/fix_network_interface_names.service
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true

- name: Start fix_network_interface_names.service
  ansible.builtin.systemd:
    name: fix_network_interface_names.service
    enabled: true
    state: started
    daemon_reload: true
  become: true

#
# Network Manager is a mess and not idempotent in most cases creating yet another config.
#
# - name: Create network connection with nmcli.
#   community.general.nmcli:
#     conn_name: "{{ item['device'] }}"
#     ifname: "{{ item['device'] }}"
#     type: ethernet
#     method4: "{{ item['method4'] }}"
#     method6: disabled
#     state: present
#     autoconnect: true
#   loop: "{{ interfaces }}"
#   become: true
...
