---
ip_addresses:
  reception:
    vlan1337:
      address: 172.23.68.181
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    vlan16:
      address: 195.169.22.179
      netmask: /32
      fqdn: 'reception.hpc.rug.nl'
  talos:
    tl_internal_management:
      address: 10.10.1.30
      netmask: /32
    vlan1068:
      address: 172.23.60.30
      netmask: /32
    vlan1337:
      address: 172.23.68.35
      netmask: /32
  tl-chaperone:
    vlan1337:
      address: 172.23.68.95
      netmask: /32
  tl-dai:
    vlan1068:
      address: 172.23.60.21
      netmask: /32
    vlan1337:
      address: 172.23.68.224
      netmask: /32
  tl-node-a01:
    vlan1068:
      address: 172.23.60.11
      netmask: /32
    vlan1337:
      address: 172.23.68.9
      netmask: /32
  tl-node-b01:
    vlan1068:
      address: 172.23.60.24
      netmask: /32
    vlan1337:
      address: 172.23.68.137
      netmask: /32
  tl-node-c01:
    vlan1068:
      address: 172.23.60.23
      netmask: /32
    vlan1337:
      address: 172.23.68.73
      netmask: /32
  tl-repo:
    vlan1337:
      address: 172.23.68.3
      netmask: /32
  tl-sai:
    vlan1068:
      address: 172.23.60.8
      netmask: /32
    vlan1337:
      address: 172.23.68.66
      netmask: /32
  tl-transfer:
    vlan1337:
      address: 172.23.68.144
      netmask: /32
      fqdn: 'tl-transfer'  # Not really a FQDN as there is no public IP: only for internal use / testing.
  tl-test:
    vlan1337:
      address: 172.23.68.170
      netmask: /32
      fqdn: 'tl-test'  # Not really a FQDN as there is no public IP: only for internal use / testing.
  tl_internal_management-vlan16-router:
    tl_internal_management:
      address: 10.10.1.1
      netmask: /32
    vlan16:
      address: 195.169.22.49
      netmask: /32
      fqdn: 'NXDOMAIN'
  vlan1337-vlan16-router:
    vlan1337:
      address: 172.23.68.1
      netmask: /32
    vlan16:
      address: 195.169.22.56
      netmask: /32
      fqdn: 'NXDOMAIN'
...
