---
- name: Restart ega-fuse-client service instances.
  systemd:
    name: "ega-fuse-client@{{ item.key }}.service"
    state: 'restarted'
    daemon_reload: 'yes'
  with_dict: "{{ ega_fuse_client_mounts }}"
  become: true
  listen: restart_ega-fuse-client
...
