---
- name: Install spacewalk client repo.
  yum:
   name: http://yum.spacewalkproject.org/2.4-client/RHEL/7/x86_64/spacewalk-client-repo-2.4-3.el7.noarch.rpm
   state: present

- name: load secrets
  include_vars: secrets.yml

- name: install spacewalk client packages.
  yum:
   name: "{{item}}"
  with_items:
   - rhn-client-tools
   - rhn-check
   - rhn-setup
   - rhnsd
   - m2crypto
   - yum-rhn-plugin

- name: hack to patch spacewalk client
  get_url:
   url: https://raw.githubusercontent.com/spacewalkproject/spacewalk/361efdfda34b381157b11bde1e7fcd06c64347c9/client/rhel/rhn-client-tools/src/up2date_client/hardware_gudev.py
   dest: /usr/share/rhn/up2date_client/hardware_gudev.py

- name: restart spacewalk daemon
  systemd:
   name: rhnsd.service
   state: restarted

- name: register at the spacewalk server
  rhn_register:
   state: present
   activationkey: "{{activation_key}}"
   server_url: "{{server_url}}"
   channels: "{{rhn_channels}}"
  register: result
  until: result is succeeded
  retries: 3
  delay: 3
  ignore_errors: yes

- name: upgrade all packages
  yum:
   name: '*'
   state: latest
