---
#
# ToDo: this may fail when deploying a cluster from scratch
# when DNS resolving is not yet properly configured resulting in:
# 'Failure downloading https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.8-client/\
#  epel-7-x86_64/00742644-spacewalk-repo/spacewalk-client-repo-2.8-11.el7.centos.noarch.rpm,
#  Request failed: <urlopen error [Errno -2] Name or service not known>'
#
- name: 'Install spacewalk client repo.'
  yum:
    name: "https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/\
           spacewalk-2.8-client/epel-7-x86_64/00742644-spacewalk-repo/spacewalk-client-repo-2.8-11.el7.centos.noarch.rpm"
    state: present
  become: true

- name: 'Install spacewalk client packages.'
  yum:
    name:
      - 'rhn-client-tools'
      - 'rhn-check'
      - 'rhn-setup'
      - 'rhnsd'
      - 'm2crypto'
      - 'yum-rhn-plugin'
  notify:
    - 'restart_rhnsd'
  become: true

- name: 'Enable spacewalk service.'
  systemd:
    name: 'rhnsd.service'
    enabled: true
    state: started
  notify:
    - 'restart_rhnsd'
  become: true

- name: 'Flush handlers.'
  meta: flush_handlers

- name: 'Register client at the spacewalk server.'
  rhn_register:
    state: present
    activationkey: "{{ activation_key }}"
    server_url: "{{ spacewalk_server_url }}"
    channels: "{{ rhn_channels }}"
  register: result
  until: result is succeeded
  retries: 3
  delay: 3
  ignore_errors: true
  no_log: true
  become: true

- name: 'Disable gpgcheck for spacewalk repo.'
  lineinfile:
    path: '/etc/yum/pluginconf.d/rhnplugin.conf'
    regexp: '^gpgcheck = [0-9].*'
    line: 'gpgcheck = 0'
    owner: root
    group: root
    mode: '0644'
  become: true

- name: 'Remove all (non-spacewalk) repo config files from /etc/yum.repos.d/.'
  shell: 'rm -rfv /etc/yum.repos.d/*'
  args:
    warn: false
  register: deleted_items
  changed_when: deleted_items.stdout | length >= 1
  failed_when: deleted_items.stderr | length >= 1
  become: true
...
