---
- name: 'Setting service_name fact.'
  set_fact:
    service_name: prometheus-slurm-exporter

- name: 'Create directory for Prometheus.'
  file:
    path: '/usr/local/prometheus'
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: "Install Prometheus {{ service_name }} binary."
  copy:
    src: "{{ playbook_dir }}/promtools/results/{{ service_name }}"
    dest: "/usr/local/prometheus/{{ service_name }}"
    mode: '0755'
    owner: root
    group: root
  notify: "restart_{{ service_name }}"
  become: true

- name: "Install {{ service_name }} service file."
  template:
    src: "templates/{{ service_name }}.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: '0644'
    owner: root
    group: root
  tags:
    - service-files
  notify: "restart_{{ service_name }}"
  become: true

- name: "Make sure {{ service_name }} service is enabled and started."
  systemd:
    name: "{{ service_name }}.service"
    state: started
    enabled: true
  tags:
    - start-service
  become: true
...
