---
- name: 'Install cadvisor service file.'
  template:
    src: 'templates/cadvisor.service'
    dest: '/etc/systemd/system/cadvisor.service'
    mode: '0644'
    owner: root
    group: root
  notify: restart_cadvisor
  become: true

- name: 'Make sure cadvisor service is enabled and started.'
  systemd:
    name: 'cadvisor.service'
    state: started
    enabled: true
    daemon_reload: true
  become: true
...
