---
openstack_api_timeout: 180
#
# security_group_names_of_all_hosts_created_in_openstack are the hosts specified in the inventory,
# which also have a `cloud_flavor` specified, indicating these machines are created in OpenStack.
#
security_group_names_of_all_hosts_created_in_openstack: "{{ hostvars
    | json_query('* | [?cloud_flavor] | [].host_networks[].security_group')
    | flatten
    | unique }}"
...
