---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: 'archive_systemd_reload'
  become: true

- name: Enable and start automounts
  ansible.builtin.systemd_service:
    name: "{{ item + '.automount' }}"
    state: started
    enabled: true
  listen: 'archive_automount_enable'
  with_items: "{{ desired_auto_mounts }}"
  become: true
...
