---
- name: Import pre deploy checks.
  ansible.builtin.import_playbook: ../single_group_playbooks/pre_deploy_checks.yml

- name: Import cgroups single role playbook.
  ansible.builtin.import_playbook: ../single_role_playbooks/cgroups.yml

- name: Import regular_users single role playbook.
  ansible.builtin.import_playbook: ../single_role_playbooks/regular_users.yml

- name: Import shared_storage single role playbook.
  ansible.builtin.import_playbook: ../single_role_playbooks/shared_storage.yml

- name: Import slurm single role playbook.
  ansible.builtin.import_playbook: ../single_role_playbooks/slurm.yml

- name: Import subgroup_directories single role playbook.
  ansible.builtin.import_playbook: ../single_role_playbooks/subgroup_directories.yml
...
