---
- name: Include variable
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/{{ each_ssh_config }}"
    name: ssh_client_settings_for_external_stack
  delegate_to: localhost
  connection: local
  run_once: true

- name: Add this key to all_CAs
  ansible.builtin.set_fact:
    all_CAs: "{{ all_CAs | default([]) + [ ssh_client_settings_for_external_stack['ssh_client_known_hosts'] ] }}"
  delegate_to: localhost
  connection: local
  run_once: true


- name: "Create /etc/ssh/ssh_config.d/{{ each_stack }}.conf config file."
  ansible.builtin.template:
    src: ssh_client_config.j2
    dest: "/etc/ssh/ssh_config.d/{{ each_stack }}.conf"
    owner: root
    group: root
    mode: '0644'
  when:
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is defined
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is not none
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] | default('') | length >= 1
  become: true
...
