---
- name: Create /etc/ssh/ssh_config.d/ dir.
  ansible.builtin.file:
    path: /etc/ssh/ssh_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  when:
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is defined
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] is not none
    - ssh_client_settings_for_external_stack['ssh_client_jumphosts'] | default('') | length >= 1
  become: true

- name: Find all directories in group_vars
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/group_vars/"
    file_type: directory
    recurse: false
  register: all_groups_dirs
  connection: local
  run_once: true

- name: Extract directory name, except 'all' and 'template'
  ansible.builtin.set_fact:
    all_stacks_names: "{{ all_groups_dirs.files | map(attribute='path') | map('basename') | reject('in', ['template', 'all']) | list }}"

- name: Find files names ssh_client_settings.yml inside those directories
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/group_vars/{{ item }}"
    patterns: "ssh_client_settings.yml"
    recurse: true
  loop: "{{ all_stacks_names }}"
  register: local_ssh_client_configs
  connection: local
  run_once: true

- name: Configure variables
  ansible.builtin.set_fact:
    local_ssh_configs_paths: "{{ local_ssh_client_configs.results | json_query('[*].files[*].path') }}"
    public_certificate_authorities: []

- name: Iterate over every stack and configure ssh client
  ansible.builtin.include_tasks:
    file: collect_stack_info_create_ssh_configs.yml
  loop: "{{ local_ssh_configs_paths }}"
  loop_control:
    label: "{{ item if item is not none }}"
  vars:
    each_ssh_config: "{{ item | regex_search('(group_vars\/.*\\.yml)', '\\1') | first }}"
    each_stack: "{{  item | regex_search('group_vars\/(.*)\/ssh_client_settings.yml', '\\1') | first }}"
  when: item | length > 0

- name: Find matching files
  ansible.builtin.find:
    paths: "/etc/ssh/ssh_config.d/"
    file_type: file
    patterns: "*.LoR.conf"
  register: remote_ssh_conf_paths
  become: true

- name: Make a filename list of remote LoR configs
  ansible.builtin.set_fact:
    remote_ssh_confs: "{{ remote_ssh_conf_paths.files | map(attribute='path') | map('basename') | list }}"
    local_ssh_configs_formatted: "{{ local_ssh_configs_paths
        | flatten
        | map('regex_replace', '^.*group_vars/', '')
        | map('regex_replace', '/ssh_client_settings.yml$', '')
        | map('regex_replace', '$', '.LoR.conf')
        | list }}"

- name: Create list of remote .LoR.conf files to be removed
  ansible.builtin.set_fact:
    remote_remove_ssh_confs: "{{ remote_ssh_confs | difference(local_ssh_configs_formatted) }}"

- name: Remove .LoR.conf files
  ansible.builtin.file:
    path: "/etc/ssh/ssh_config.d/{{ item }}"
    state: absent
  loop: "{{ remote_remove_ssh_confs }}"
  become: true

- name: Deploy a block of all public CAs into /etc/ssh/ssh_known_hosts file
  ansible.builtin.blockinfile:
    path: /etc/ssh/ssh_known_hosts
    marker: "## {mark} ANSIBLE MANAGED BLOCK - DO NOT CHANGE IT ##"
    insertafter: EOF
    mode: '0644'
    block: |
      {% for ca in public_certificate_authorities | sort %}
      {{ ca }}
      {% endfor %}
    create: true
  become: true
...
