---
#
# We only check if the envsync account for deploy admins exists; Hence we DO NOT create it here!
# Depending on wether this account comes from an LDAP or is a local account,
# it must have been created earlier on in the play.
#
- name: 'Check if envsync group is present (without creating one if not existing yet).'
  group:
    name: "{{ envsync_group }}"
    state: present
  become: false

- name: 'Check if envsync user is present (without creating one if not existing yet).'
  user:
    name: "{{ envsync_user }}"
    group: "{{ envsync_user }}"
    groups: "{{ envsync_group }}"
    home: "/home/{{ envsync_user }}"
    create_home: false
    append: false
  become: false

#
# Configure environment synchronization account.
#
- name: 'Initialize envsync account creating home dir if it did not exist yet.'
  command:
    cmd: "mkhomedir_helper {{ envsync_user }} 0077"
    creates: "/home/{{ envsync_user }}"
  become: true

- name: 'Allow passwordless sudo to the environment synchronization account for deploy admin users.'
  lineinfile:
    dest: '/etc/sudoers'
    line: "%{{ envsync_group }}    ALL=({{ envsync_user }})    NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  become: true

- name: 'Insert/update block into ~/.bashrc to ensure we use the correct environment for syncing.'
  blockinfile:
    dest: "/home/{{ envsync_user }}/.bashrc"
    block: |
      [ $(id -gn) = {{ envsync_group }} ] || exec newgrp {{ envsync_group }}
      cd
      umask 0002
      module load depad-utils
      module list
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Setup environment for environment synchronization account."
    insertafter: EOF
    create: false
  become: true

- name: 'Deploy script to verify and if necessary fix prmissions of the environment managed by the envsync account.'
  template:
    src: 'templates/hpc-environment-permissions.bash'
    dest: '/root/hpc-environment-permissions.bash'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true

- name: 'Create cron job to execute script to verify and if necessary fix prmissions of the environment managed by the envsync account.'
  cron:
    name: Verify and fix permissions for HPC environment.
    weekday: '*'
    hour: '04'
    minute: '04'
    user: 'root'
    job: '/bin/bash /root/hpc-environment-permissions.bash'
    cron_file: 'hpc-environment-permissions'
  become: true

- name: 'Create cron job to synchronise the environment managed by the envsync account.'
  cron:
    name: Synchronise HPC environment.
    weekday: '*'
    hour: '05'
    minute: '05'
    user: "{{ envsync_user }}"
    job: |
         /usr/bin/sg {{ envsync_group }} -c '/bin/bash -c "export SOURCE_HPC_ENV="True"; . ~/.bashrc; hpc-environment-sync.bash -a"'
    cron_file: 'hpc-environment-sync'
  become: true
...
