---
#
# INSTALL auto-subgroups structure scripts
#
- name: Deploy lsaai_auth secrets into /etc/lsaai_auth
  ansible.builtin.template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - name: lsaai_auth
      path: /etc
      mode: "0640"
    - name: lsaai_request_token.sh
      path: /usr/local/sbin
      mode: "0750"
    - name: subgroup_directories_auto.sh
      path: /usr/local/sbin
      mode: "0750"
    - name: lsaai_subgroups.sh
      path: /usr/local/bin
      mode: "0755"
  become: true
  when: subgroup_directories_auto

- name: Deploying systemd services for auto-generating subgroup directories
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "0640"
  with_items:
    - subgroup_directories_auto.path
    - subgroup_directories_auto.timer
    - subgroup_directories_auto.service
  notify:
    - subgroup_directories_auto_reload_systemd
    - subgroup_directories_auto_enable_service
    - subgroup_directories_auto_enable_timer
    - subgroup_directories_auto_enable_path
  become: true
  when: subgroup_directories_auto

- name: Allow all users to make lsaai token request via sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/92-ansible-managed-lsaai_request_token
    owner: root
    group: root
    mode: "0440"   # sudoers files must be exactly 0440
    content: |
      # Allow any user to run reveal_secret with no password
      # NOPASSWD with full path and prevent arguments
      ALL ALL=(root) NOPASSWD: /usr/local/sbin/lsaai_request_token.sh
    validate: /usr/sbin/visudo -cf %s
  become: true
  when: subgroup_directories_auto

#
# UN-INSTALL auto-subgroups structure scripts
#
- name: Stop and disable subgroup_directories_auto systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - subgroup_directories_auto.service
    - subgroup_directories_auto.path
    - subgroup_directories_auto.timer
  become: true
  when: subgroup_directories_auto is false

- name: Remove lsaai_auth config and scripts
  ansible.builtin.file:
    path: "{{ item.path }}/{{ item.name }}"
    state: absent
  with_items:
    - name: lsaai_auth
      path: /etc
    - name: lsaai_request_token.sh
      path: /usr/local/sbin
    - name: subgroup_directories_auto.sh
      path: /usr/local/sbin
    - name: lsaai_subgroups.sh
      path: /usr/local/bin
  become: true
  when: subgroup_directories_auto is false

- name: Remove systemd unit files
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  with_items:
    - subgroup_directories_auto.path
    - subgroup_directories_auto.timer
    - subgroup_directories_auto.service
  become: true
  when: subgroup_directories_auto is false

- name: Reload systemd daemon to drop removed units
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  when: subgroup_directories_auto is false

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
...
