---
- name: Create versioned projects and releases
  ansible.builtin.include_tasks:
    file: versions_and_projects_main.yml

- name: Deploy hieararchical structure tools
  ansible.builtin.include_tasks:
    file: hierarchical_auto_ldap_structure.yml
...
