---
- debug:
    msg: "{{ item }}"
  loop: "{{ yum_repo }}"

#- meta: end_play


- name: "Configure all options for all repos in {{ yum_repo }}"
  community.general.ini_file:
    path: "/mnt/repos/dnf.repos.d/{{ yum_repo }}/{{ repo.file }}"
    section: "{{ repo.id }}"
    no_extra_spaces: true
    create: true
    option: "{{ opt }}"
    value: "{{ repo[opt] }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "{{ yum_repos[item]
          | selectattr('enabled', 'defined')
          | selectattr('enabled', 'equalto', 1)
          | map(attribute='id')
          | list }}"
    - "{{ yum_repos[item] | product(options) | list }}"
  loop_control:
    label: "{{ repo.file }}:{{ opt }}"
  vars:
    options:
      - name
      - baseurl
      - mirrorlist
      - metalink
      - enabled
      - countme
    repo: "{{ item.0 }}"
    opt: "{{ item.1 }}"
#  when: repo[opt] is defined
  become: true
...
