---
- name: "Deploy repository management scripts to {{ main_repo_path }}"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ main_repo_path }}/{{ item }}"
    owner: root
    group: root
    mode: '0750'
  with_items:
    - 1_sync_repo_to_new_version.sh
    - 2_new_repo_distribution.sh
    - 3_cleanup.sh
  become: true

- name: "Create the folder structure for the repository configuration files"
  ansible.builtin.file:
    path: "{{ main_repo_path }}/dnf/repos.d"
    state: directory
    mode: '0750'
    owner: 'root'
    group: 'root'
  loop:
     - "{{ main_repo_path }}/dnf/repos.d"
     - "{{ main_repo_path }}/dnf/cache"
     - "{{ main_repo_path }}/logs/dnf"
     - "{{ main_repo_path }}/logs/scripts"
  become: true

- name: "Configure repo for each distribution"
  ansible.builtin.include_tasks: configure_repo_options.yml
  loop: "{{ yum_repos | list }}"
  loop_control:
    loop_var: this_distribution
...
