---
- name: Enable / restart nvidia-persistenced service
  ansible.builtin.systemd:
    name: nvidia-persistenced.service
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  listen: 'nvidia_service'

- name: Rebuild initramfs
  ansible.builtin.command: dracut -f
  notify: reboot_server
  register: dracut_reg
  changed_when: dracut_reg.rc == 0
  listen: 'dracut'
  become: true

- name: Restart server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
  listen: 'reboot_server'
  become: true
...
