---
- name: Create mount files from templates
  ansible.builtin.template:
    src: create-ldap-subgroups.sh.j2
    dest: /usr/local/sbin/create-ldap-subgroups.sh
    owner: root
    group: root
    mode: "0750"
  become: true
...
