---
- name: >
    Set the various interfaces in facts. This step will result in
    variables like external_interface and management_interface
    which contain the interfcace name. e.g. eth0
  set_fact: {"{{ item[1] + '_interface' }}":"{{ item[0] }}"}
  when: >
    (hostvars[inventory_hostname]['ansible_%s' % item[0]]|default({}))
    .get('ipv4', {}).get('network') == item[2]
  with_nested:
    - "{{ ansible_interfaces }}"
    - "{{ networks | dictsort}}"

- debug:
    msg: >
      found interface for {{ item }}
      with address {{ hostvars[item] }}
  with_items:
    - management_interface
    - storage_interface
    - external_interface
