---
- name: Debug OS
  debug:
    msg: "Configuring firewall for {{ ansible_facts['os_family'] }}"

- name: Include UFW tasks for Debian/Ubuntu
  import_tasks: ufw.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include existing firewalld role for Rocky/RHEL
  include_role:
    name: iptables
  when: ansible_facts['os_family'] == "RedHat"
