---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes
  become: true

- name: Reset UFW configuration (safe and idempotent)
  command: ufw --force reset
  changed_when: false
  become: true

- name: Set default policies
  ufw:
    direction: incoming
    policy: deny
  become: true

- name: Set outgoing policy
  ufw:
    direction: outgoing
    policy: allow
  become: true

#- name: Allow ICMP (ping) globally
#  command: ufw allow proto icmp
#  become: yes
#  changed_when: false

- name: Allow tcp from specific IPs and ports
  ufw:
    rule: allow
    port: "{{ item.1 }}"
    from_ip: "{{ item.0 }}"
    proto: tcp
  loop: "{{ iptables_allow_ssh_inbound | product(firewall_allowed_ports) | list }}"
  notify: restart_ufw
  become: true

- name: Allow incoming access internal interfaces   
  community.general.ufw:
    rule: allow
    interface: "{{ item }}"
    direction: in
  loop: "{{ firewall_internal_interfaces }}"
  notify: restart_ufw
  become: true

- name: Enable UFW (if not already)
  ufw:
    state: enabled
    logging: 'on'
  become: true
