---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes
  become: true

- name: Reset UFW configuration (safe and idempotent)
  command: ufw --force reset
  changed_when: false
  become: true

- name: Set default policies
  ufw:
    direction: incoming
    policy: deny
  become: true

- name: Set outgoing policy
  ufw:
    direction: outgoing
    policy: allow
  become: true

- name: Allow essential ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ firewall_allowed_ports }}"
  notify: restart_ufw
  become: true

#- name: Allow SSH only from admin IP
#  ufw:
#    rule: allow
#    port: 22
#    proto: tcp
#    from_ip: "{{ firewall_admin_ip }}"
#  become: true

#- name: Allow all traffic on internal interfaces
#  ufw:
#    rule: allow
#    in_interface: "{{ item }}"
#    out_interface: "{{ item }}"
#  loop: "{{ firewall_internal_interfaces }}"
#  notify: restart_ufw
#  become: true

- name: Allow incoming access internal interfaces   
  community.general.ufw:
    rule: allow
    interface: "{{ item }}"
    direction: in
  loop: "{{ firewall_internal_interfaces }}"
  notify: restart_ufw
  become: true

- name: Enable UFW (if not already)
  ufw:
    state: enabled
    logging: 'on'
  become: true
