---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes
  become: true

# UFW does NOT break existing established connections.
- name: Reset UFW configuration
  ansible.builtin.command: ufw --force reset
  changed_when: false
  become: true

- name: Set default policies
  community.general.ufw:
    direction: incoming
    policy: deny
  become: true

- name: Set outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: allow
  become: true

# - name: Allow tcp from specific IPs and ports
#   community.general.ufw:
#     rule: allow
#     port: "{{ item.1 }}"
#     interface: "{{ item.2 | string}}"
#     direction: in
#     from_ip: "{{ item.0.address | regex_replace('\\d+$', '0') }}{{ item.0.netmask }}"
#     proto: tcp
#   loop: "{{ iptables_allow_ssh_inbound | product(firewall_allowed_ports) | product(firewall_internal_interfaces) | map('flatten') | list }}"
#   notify: restart_ufw
#   become: true

- name: Allow tcp from specific IPs and ports
  community.general.ufw:
    rule: allow
    port: "{{ item.1 }}"
    interface: "{{ item.2 }}"
    direction: in
    from_ip: >-
      {{
        item.0.publicly_exposed
          | default(false)
          | ternary(
              item.0.address,
              item.0.address | regex_replace('\\d+$', '0') ~ item.0.netmask
            )
      }}
    proto: tcp
  loop: "{{ iptables_allow_ssh_inbound | product(firewall_allowed_ports) | product(firewall_internal_interfaces) | map('flatten') | list }}"
  notify: restart_ufw
  become: true

- name: Enable UFW (if not already)
  community.general.ufw:
    state: enabled
    logging: 'on'
  become: true
