---
# First install postfix to avoid issues with esmtp package
- name: Install postfix (needed by fail2ban)
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "postfix", state: "latest" }
    - { name: "esmtp", state: "absent" }
  become: true

- name: Ensure that postfix is running and enabled on boot
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Install fail2ban.
  ansible.builtin.package:
    name: fail2ban
    state: present
  become: true

- name: Copy fail2ban custom configuration file into place.
  ansible.builtin.template:
    src: "{{ basic_security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure fail2ban is running and enabled on boot.
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  become: true
...
