---
ip_addresses:
  hc-dai:
    hc_internal_management:
      address: 10.10.1.252
      netmask: /32
    lustre:
      address: 172.23.13.202
      netmask: /32
  hc-node-a01:
    hc_internal_management:
      address: 10.10.1.18
      netmask: /32
    lustre:
      address: 172.23.12.201
      netmask: /32
  hc-repo:
    hc_internal_management:
      address: 10.10.1.87
      netmask: /32
  hc-sai:
    hc_internal_management:
      address: 10.10.1.111
      netmask: /32
    lustre:
      address: 172.23.12.245
      netmask: /32
  hyperchicken:
    hc_internal_management:
      address: 10.10.1.54
      netmask: /32
    lustre:
      address: 172.23.13.230
      netmask: /32
  portal:
    hc_internal_management:
      address: 10.10.1.37
      netmask: /32
      publicly_exposed: true  # This internal IP is linked to a public (floating) IP.
    external_unfiltered:
      address: 194.171.202.199
      netmask: /32
      fqdn: 'bateleur131.hpc.rug.nl'
  hc_internal_management-external_unfiltered-router:
    hc_internal_management:
      address: 10.10.1.1
      netmask: /32
    external_unfiltered:
      address: 194.171.202.218
      netmask: /32
      fqdn: 'NXDOMAIN'
...
