---
slurm_cluster_name: 'hyperchicken'
slurm_cluster_domain: ''
stack_prefix: 'hc'
slurm_version: '18.08.8-1.el7.umcg'
repo_manager: 'pulp'
mailhub: '192.168.0.5'
rewrite_domain: "{{ stack_prefix }}-sai{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
figlet_font: 'lockergnome'
motd: "To solve or not to solve, that's the question."
additional_etc_hosts:
  - group: all
    hosts:
      - docs
vcompute_hostnames: "{{ stack_prefix }}-vcompute01"
vcompute_sockets: 16
vcompute_cores_per_socket: 1
vcompute_real_memory: 64264
vcompute_max_cpus_per_node: "{{ vcompute_sockets * vcompute_cores_per_socket - 2 }}"
vcompute_max_mem_per_node: "{{ vcompute_real_memory - vcompute_sockets * vcompute_cores_per_socket * 512 }}"
vcompute_local_disk: 0
vcompute_features: 'tmp09'
vcompute_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ui_hostnames: "{{ slurm_cluster_name }}"
ui_sockets: 4
ui_cores_per_socket: 1
ui_real_memory: 7821
ui_local_disk: 0
ui_features: 'prm09,tmp09'
ui_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/umcg-hpc-development-ca"
use_ldap: yes
create_ldap: yes
ldap_uri: ldap://hc-dai
ldap_base: dc=hpc,dc=rug,dc=nl
ldap_binddn: cn=admin,dc=hpc,dc=rug,dc=nl
ldap_domain: hpc.rug.nl
cloud_image: CentOS7-Cloud
cloud_user: centos
flavor_jumphost: 1c2m20d # s1.small
flavor_ui: 4c8m80d # s1.large
flavor_vcompute: 8c16m80d
flavor_management: 4c4m60d
network_public_external_id: public
network_private_management_id: "{{ stack_prefix }}_internal_management"
network_private_management_cidr: '10.10.1.0/24'
network_private_management_gw: '10.10.1.1'
network_private_storage_id: "{{ stack_prefix }}_internal_storage"
network_private_storage_cidr: '10.10.2.0/24'
public_ip_addresses:
  portal: '45.88.81.146'
availability_zone: nova
local_volume_size_repo: 30
local_volume_size_vcompute: 1
local_volume_size_management: 1
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'marloes'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
envsync_user: 'envsync'
envsync_group: 'depad'
hpc_env_prefix: '/apps'
regular_groups:
  - 'users'
  - 'depad'
  - 'solve-rd'
  - 'umcg-atd'
regular_users:
  - user: 'envsync'
    groups: ['depad']
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
    sudoers: '%solve-rd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'gvdvries'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'scimerman'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
#
# Shared storage related variables
#
pfs_mounts: [
  { pfs: 'ecst01',
    source: 'em-isi-3126.ebi.ac.uk:/ifs/Solve-RD',
    type: 'nfs',
    rw_options: 'defaults,_netdev,noatime,nodiratime',
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro' },
]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'ecst01',
    machines: "{{ groups['cluster'] }}" },
  { lfs: 'tmp09',
    pfs: 'ecst01',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'prm09',
    pfs: 'ecst01',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'env09',
    pfs: 'ecst01',
    machines: "{{ groups['compute_vm'] + groups['user_interface'] }}" },
]
ega_fuse_client_mounts:
  solve_rd: '/groups/solve-rd/prm09/ega-fuse-client'
ega_fuse_client_java_home: '/apps/software/AdoptOpenJDK/8u222b10-hotspot'
interfaces:
  - device: 'eth0'
    bootproto: 'dhcp'
  - device: 'eth1' 
    bootproto: 'dhcp'
...
