---
stack_prefix: 'p2solo'
stack_name: "{{ stack_prefix }}_server"  # stack_name must match the name of the folder that contains this vars.yml file.
cloud_user: ubuntu
os_distribution: 'Ubuntu24'
repo_manager: 'none'
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'grid'
use_ldap: false
create_ldap: false
use_sssd: false
autoupdate_enabled: false
ssh_daemon_name: ssh
basic_security_sshd_name: "{{ ssh_daemon_name }}"
