#
# Install webserver and deploy cluster specific documentation on that web server.
#
---
- name: 'Check OS version of target host.'
  fail:
    msg: 'This role requires RedHat/CentOS version >= 7.x'
  when: ansible_facts['os_family'] != "RedHat" or ansible_facts['distribution_major_version'] <= "6"

#
# This is currently problematic when
# * the default user used to login to the cluster is different from
# * the default user used to login on the webserver where the docs are hosted
# as you can specify only one account name with -u on the commandline when running ansible-playbook.
#
- name: 'Gather facts from hosts, so we can use them in the generated docs.'
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items:
    - "{{ groups['jumphost'] }}"
    - "{{ groups['user_interface'] }}"

- name: 'Get Slurm version from scontrol on UI.'
  shell:
    cmd: |
      set -o pipefail
      scontrol version | head -n 1 | sed 's|^slurm *\([0-9\.]*\).*$|\1|' | tr -d '\n'
  args:
    executable: '/bin/bash'
    warn: false
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  delegate_to: "{{ groups['user_interface'] | first }}"
  changed_when: false
  failed_when: false
  check_mode: false
  register: 'slurm_version'

- name: 'Get Lmod version from UI.'
  #
  # Example output:
  # Modules based on Lua: Version 6.5.8  2016-09-03 13:41 -05:00 (CDT)
  #    by Robert McLay mclay@tacc.utexas.edu
  #
  shell:
    cmd: |
      set -o pipefail
      unset MODULEPATH
      source ~/.modulesrc >/dev/null 2>&1
      lmod -v | sed '/^$/d' | sed 's|^.*Version \([0-9\.]*\).*$|\1|' | head -1
  args:
    executable: '/bin/bash'
    warn: false
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  delegate_to: "{{ groups['user_interface'] | first }}"
  changed_when: false
  failed_when: false
  check_mode: false
  register: 'lmod_version'

- name: "Find all ip_addresses.yml files in {{ playbook_dir }}/group_vars/*."
  find:
    paths: "{{ playbook_dir }}/group_vars/"
    recurse: true
    patterns: 'ip_addresses.yml'
  register: ip_addresses_files
  delegate_to: localhost

- name: 'Include variables from all ip_addresses.yml files.'
  include_vars:
    file: "{{ item }}"
    name: "networking_lookup"
  with_items: "{{ ip_addresses_files.files | map (attribute='path') | list }}"
  register: networking_lookups
  delegate_to: localhost

- name: 'Combine network info from ip_addresses.yml files into one dict.'
  set_fact:
    networking_lookups: "{{ networking_lookups.results | json_query('[].ansible_facts.networking_lookup.ip_addresses') | combine() }}"
  delegate_to: localhost

- name: 'Set selinux in permissive mode.'
  selinux:
    policy: 'targeted'
    state: 'permissive'
  become: true

- name: 'Install EPEL repo and rsync.'
  yum:
    state: 'latest'
    update_cache: true
    name:
      - 'epel-release'
      - 'rsync'
  become: true

- name: 'Install webserver and php.'
  yum:
    state: 'latest'
    update_cache: true
    name:
      - 'php'
      - 'httpd'
  notify:
    - 'restart_httpd'
  become: true

- name: 'Enable webserver.'
  service:
    name: "{{ item }}"
    enabled: true
    state: 'started'
  with_items:
    - 'httpd'
  become: true

- name: 'Install MkDocs on RedHat 7.x.'
  include_tasks:
    file: mkdocs-for-redhat7.yml
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] >= "7"

- name: 'Create base directories for MarkDown and HTML files.'
  file:
    path: "{{ item.path }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: "{{ item.mode }}"
  with_items:
    - path: "/srv/mkdocs/{{ slurm_cluster_name }}/"
      mode: '0750'
    - path: "/srv/mkdocs/{{ slurm_cluster_name }}/tmp/"
      mode: '0750'
    - path: "/srv/mkdocs/{{ slurm_cluster_name }}/docs/"
      mode: '0750'
    - path: "/srv/mkdocs/{{ slurm_cluster_name }}/docs/attachments"
      mode: '0750'
    - path: "/var/www/html/{{ slurm_cluster_name }}/"
      mode: '0755'
    - path: "/var/www/html/{{ slurm_cluster_name }}/attachments/"
      mode: '0755'
  become: true

- name: 'Create static files for index in document root.'
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/roles/online_docs/files/index//./{{ item.src }}"
    dest: "/var/www/html/"
    owner: 'no'
    group: 'no'
    use_ssh_args: true
    ssh_connection_multiplexing: true
    rsync_opts:
      # --omit-dir-times  Is required to prevent "sync error: some files/attrs were not transferred"
      #                   for file systems like NFS mounts that cannot handle setting dir times properly.
      # --chmod           Is required to prevent errors when the perms on the source are not what is required/expected on the destination.
      #                   Fixing perms on the source would be good, but that may be out of our control.
      #                   In that case --chmod ensures we get what we want on the destination.
      #                   Works only when combined with --perms.
      # --force           Is required when symlinks have changed into dirs/files or vice versa.
      #                   In that case the wrong outdated stuff has to be deleted on the destination first before the new stuff can be created.
      #                   Deleting the outdated stuff may fail without --force.
      # --relative        In combination with a "source_server:some/path/not/created/on/destination/./path/created/on/destination/some_file" (dot dir)
      #                   recreates a partial dir structure on the destination relative to the /./ dir, when it does not already exist.
      #                   Without this combination of --relative and dot dir rsync will error when the path does not exist on the destination.
      #                   IMPORTANT: src and dest paths must be absolute paths. Otherwise Ansible will expand the path itself which will remove the /./ dir.
      - '--relative'
      - '--omit-dir-times'
      - '--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r'
      - '--perms'
      - '--force'
  with_items:
    - src: 'index.php'
    - src: 'sitemap.php'
  become: true

- name: 'Create sub directory structure for MarkDown files.'
  file:
    path: "/srv/mkdocs/{{ slurm_cluster_name }}/{{ item.path }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0750'
  with_filetree: "{{ playbook_dir }}/roles/online_docs/templates/mkdocs"
  when: item.state == 'directory'
  notify:
    - 'build_mkdocs'
  become: true

- name: 'Create static files for MarkDown.'
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/roles/online_docs/files/mkdocs/docs/./{{ item.src }}"
    dest: "/srv/mkdocs/{{ slurm_cluster_name }}/docs/"
    owner: 'no'
    group: 'no'
    use_ssh_args: true
    ssh_connection_multiplexing: true
    rsync_opts:
      # --omit-dir-times  Is required to prevent "sync error: some files/attrs were not transferred"
      #                   for file systems like NFS mounts that cannot handle setting dir times properly.
      # --omit-link-times Is required to prevent "sync error: some files/attrs were not transferred"
      #                   for file systems like NFS mounts that cannot handle setting dir times properly.
      #                   Requires rsync >= 3.1.2 (default on Enterprise Linux >= 7.x).
      # --chmod           Is required to prevent errors when the perms on the source are not what is required/expected on the destination.
      #                   Fixing perms on the source would be good, but that may be out of our control.
      #                   In that case --chmod ensures we get what we want on the destination.
      #                   Works only when combined with --perms.
      # --force           Is required when symlinks have changed into dirs/files or vice versa.
      #                   In that case the wrong outdated stuff has to be deleted on the destination first before the new stuff can be created.
      #                   Deleting the outdated stuff may fail without --force.
      # --relative        In combination with a "source_server:some/path/not/created/on/destination/./path/created/on/destination/some_file" (dot dir)
      #                   recreates a partial dir structure on the destination relative to the /./ dir, when it does not already exist.
      #                   Without this combination of --relative and dot dir rsync will error when the path does not exist on the destination.
      #                   IMPORTANT: src and dest paths must be absolute paths. Otherwise Ansible will expand the path itself which will remove the /./ dir.
      - '--relative'
      - '--omit-dir-times'
      - '--omit-link-times'
      - '--chmod=Du=rwx,Dg=rx,Do-rwx,Fu=rwX,Fug=rX,Fo-rwx'
      - '--perms'
      - '--force'
  with_items:
    - src: 'css'
    - src: 'img'
  notify:
    - 'build_mkdocs'
  become: true

- name: 'Create skeleton for AppleScript apps.'
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/roles/online_docs/files/attachments/{{ item.src }}/./"
    dest: "/srv/mkdocs/{{ slurm_cluster_name }}/tmp/{{ item.dest }}"
    owner: 'no'
    group: 'no'
    use_ssh_args: true
    ssh_connection_multiplexing: true
    recursive: 'yes'
    rsync_opts:
      - '--relative'
      - '--omit-dir-times'
      - '--omit-link-times'
      - '--chmod=Du=rwx,Dg=rx,Do-rwx,Fu=rwX,Fg=rX,Fo-rwx'
      - '--perms'
      - '--force'
  with_items:
    - src: 'ssh-client-config.app'
      dest: "ssh-client-config-for-{{ slurm_cluster_name }}.app"
    - src: 'mount-cluster-drives.app'
      dest: 'mount-cluster-drives.app'
  notify:
    - 'zip_attachments'
    - 'build_mkdocs'
  become: true

- name: 'Make sure main script of AppleScript apps are executable.'
  file:
    path: "/srv/mkdocs/{{ slurm_cluster_name }}/tmp/{{ item }}/Contents/MacOS/applet"
    state: 'file'
    owner: 'root'
    group: 'root'
    mode: '0750'
  with_items:
    - "ssh-client-config-for-{{ slurm_cluster_name }}.app"
    - 'mount-cluster-drives.app'
  notify:
    - 'zip_attachments'
    - 'build_mkdocs'
  become: true

- name: 'Create files for attachments based on templates.'
  template:
    src: "attachments/{{ item.src }}"
    dest: "/srv/mkdocs/{{ slurm_cluster_name }}/tmp/{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: "{{ item.mode }}"
  with_items:
    #
    # For macOS users we inject the configuration script for this cluster into the AppleScript app skeleton.
    #
    - src: 'ssh-client-config.bash'
      dest: "ssh-client-config-for-{{ slurm_cluster_name }}.app/Contents/MacOS/ssh-client-config.command"
      mode: '0750'
    #
    # For Linux/Unix users: just generate a bare Bash script.
    #
    - src: 'ssh-client-config.bash'
      dest: "ssh-client-config-for-{{ slurm_cluster_name }}.bash"
      mode: '0750'
  notify:
    - 'zip_attachments'
    - 'build_mkdocs'
  become: true

- name: 'Create MarkDown files based on templates.'
  template:
    src: "{{ item.src }}"
    dest: "/srv/mkdocs/{{ slurm_cluster_name }}/{{ item.path }}"
    owner: 'root'
    group: 'root'
    mode: '0640'
  with_filetree: "{{ playbook_dir }}/roles/online_docs/templates/mkdocs"
  # Exclude temporary *.html preview files, which are also exlcuded in .gitignore and should not be transferred.
  when: item.state == 'file' and '.md.html' not in item.path
  notify:
    - 'build_mkdocs'
  become: true
...
