---
- name: Create software RAID from multiple devices.
  ansible.builtin.shell:
    cmd: |
         set -o pipefail
         mdadm --create "{{ volume['md']['md_device'] }}" \
               --level="{{ volume['md']['raid_level'] }}" \
               --raid-devices="{{ volume['md']['raid_devices'] }}" \
               {% if volume['md']['spare_devices'] is defined -%}
               --spare-devices="{{ volume['md']['spare_devices'] }}" \
               {% endif -%}
               {% for component_device in volume['md']['component_devices'] %}"{{ component_device }}"{% if not loop.last %} {% endif %}{% endfor %}
    creates: "{{ volume['md']['md_device'] }}"
  changed_when: "'array ' + volume['md']['md_device'] + ' started' in local_storage_mdadm_result['stdout']"
  register: local_storage_mdadm_result
  become: true
...
