---
stack_prefix: 'jenkins'
stack_name: "{{ stack_prefix }}_server"  # stack_name must match the name of the folder that contains this vars.yml file.
cloud_image: RockyLinux-9.3_xfs
cloud_user: cloud-user
availability_zone: nova
os_distribution: 'rocky9'
repo_manager: 'none'
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    router:
      next-hop-address: '10.10.1.1'
      external_network: external
    create: true
    mtu_size: '1450'
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
use_ldap: false
create_ldap: false
use_sssd: false
#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: vaxtron_cluster
    hosts:
    - hostname: foyer
      network: external
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network:  external_unfiltered
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
jenkins_plugins:
  - warnings-ng
  - name: git
    version: 5.9.0
  - name: branch-api
    version: 2.1268.v044a_87612da_8
  - name: cloudbees-folder
    version: 6.1073.va_7888eb_dd514
  - name: github-branch-source
    version: 1917.v9ee8a_39b_3d0d
  - name: analysis-model-api
    version: 13.18.0-935.v784ca_107400a_
  - name: github-api
    version: 1.330-492.v3941a_032db_2a_
  - name: git-client
    version: 6.5.0
  - name: github
    version: 1.45.0
  - name: matrix-auth
    version: 3.2.9
  - name: workflow-api
    version: 1384.vdc05a_48f535f
  - name: workflow-job
    version: 1571.vb_423c255d6d9
  - name: workflow-multibranch
    version: 821.vc3b_4ea_780798
  - name: workflow-basic-steps
    version: 1098.v808b_fd7f8cf4
  - name: workflow-durable-task-step
    version: 1464.v2d3f5c68f84c
  - name: workflow-scm-step
    version: 466.va_d69e602552b_
  - name: pipeline-stage-step
    version: 322.vecffa_99f371c
jenkins_plugins_install_dependencies: true
jenkins_prefer_lts: true
jenkins_shellcheck_version: 0.8.0
jenkins_url: 'http://localhost:8080/'
jenkins_cli_dest: '/opt/jenkins-cli.jar'
jenkins_xml_dest: '/var/lib/jenkins/xml_files/'
jenkins_projects: 
  - 'NGS_RNA'
  - 'ConcordanceCheck'
...
