---
stack_prefix: 'jenkins'
stack_name: "{{ stack_prefix }}_server"  # stack_name must match the name of the folder that contains this vars.yml file.
cloud_image: RockyLinux-9.3_xfs
cloud_user: cloud-user
availability_zone: nova
os_distribution: 'rocky9'
repo_manager: 'none'
stack_networks:
  - name: "{{ stack_prefix }}_internal_management"
    cidr: '10.10.1.0/24'
    router:
      next-hop-address: '10.10.1.1'
      external_network: external
    create: true
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
local_admin_users:
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'sandi'
  - 'wim'
use_ldap: false
create_ldap: false
use_sssd: false
#
# Jumphosts from other stack-name infra groups.
# We will restrict SSH login on port 22 to these jumphosts using OpenStack security rules.
#
external_jumphosts:
  - group: vaxtron_cluster
    hosts:
    - hostname: foyer
      network: external
  - group: talos_cluster
    hosts:
      - hostname: reception
        network: vlan16
  - group: hyperchicken_cluster
    hosts:
      - hostname: portal
        network: public
  - group: fender_cluster
    hosts:
      - hostname: corridor
        network: public
  - group: nibbler_cluster
    hosts:
      - hostname: tunnel
        network: vlan16
  - group: wingedhelix_cluster
    hosts:
      - hostname: wh-porch
        network: vlan16
  - group: betabarrel_cluster
    hosts:
      - hostname: bb-porch
        network: vlan16
  - group: copperfist_cluster
    hosts:
      - hostname: cf-porch
        network: external
jenkins_plugins:
  - warnings-ng
  - name: git
    version: 5.7.0
  - name: branch-api
    version: 2.1217.v43d8b_b_d8b_2c7
  - name: cloudbees-folder
    version: 6.1012.v79a_86a_1ea_c1f
  - name: github-branch-source
    version: 1815.v9152b_2ff7a_1b_
  - name: analysis-model-api
    version: 13.2.0
  - name: github-api
    version: 1.321-488.v9b_c0da_9533f8
  - name: git-client
    version: 6.1.3
  - name: github
    version: 1.43.0
  - name: matrix-auth
    version: 3.2.6
  - name: workflow-api
    version: 1371.ve334280b_d611
  - name: workflow-job
    version: 1520.v56d65e3b_4566
  - name: workflow-multibranch
    version: 806.vb_b_688f609ee9
  - name: workflow-basic-steps
    version: 1079.vce64b_a_929c5a_
  - name: workflow-durable-task-step
    version: 1405.v1fcd4a_d00096
  - name: workflow-scm-step
    version: 437.v05a_f66b_e5ef8
  - name: pipeline-stage-step
    version: 322.vecffa_99f371c

jenkins_plugins_install_dependencies: true
jenkins_prefer_lts: true
jenkins_shellcheck_version: 0.8.0
jenkins_url: 'http://localhost:8080/'
jenkins_cli_dest: '/opt/jenkins-cli.jar'
jenkins_xml_dest: '/var/lib/jenkins/xml_files/'
jenkins_projects: 
  - 'GAP'
  - 'NGS_DNA'
  - 'NGS_RNA'
  - 'ConcordanceCheck'
...
