---
- name: Set /etc/hosts
  template:
    src: templates/hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true

- name: set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
