---
- name: Set /etc/hosts
  template:
    src: templates/hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true

- name: Set hostname to inventory_hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: make endpoints to mount isilon storage on.
  file:
    path: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - /apps
    - /.envsync/umcgst10/apps
    - /home

- name: Mount isilon apps
  mount:
    path: /apps
    src: gcc-storage001.stor.hpc.local:/ifs/rekencluster/umcgst10/apps
    fstype: nfs
    opts: defaults,_netdev,nolock,vers=4.0,noatime,nodiratime
    state: present

- name: Mount isilon home
  mount:
    path: /home
    src: gcc-storage001.stor.hpc.local:/ifs/rekencluster/umcgst10/home
    fstype: nfs
    opts: defaults,_netdev,nolock,vers=4.0,noatime,nodiratime
    state: present

- name: mount all mountpoints in fstab
  command: mount -a
  args:
    warn: false

- name: check if the lustre client is present locally
  stat:
    path: /tmp/sugarsnax/root/rpmbuild/RPMS/noarch/lustre-client-dkms-2.11.0-1.el7.centos.noarch.rpm
  register: local_file
  delegate_to: localhost

- name: check if the buildserver has already built the client.
  stat:
    path: /root/rpmbuild/RPMS/noarch/lustre-client-dkms-2.11.0-1.el7.centos.noarch.rpm
  become: true
  delegate_to: sugarsnax
  register: remote_file
  when: local_file.stat.exists == false

- name: build the lustre client.
  block:
    - name: Fetch the lustre client source
      get_url:
        url: https://downloads.whamcloud.com/public/lustre/lustre-2.11.0/el7.4.1708/client/SRPMS/lustre-client-dkms-2.11.0-1.el7.src.rpm
        dest: /tmp/lustre-client-dkms-2.11.0-1.el7.src.rpm

    - name: build the lustre client.
      command: rpmbuild --rebuild --without servers /tmp/lustre-client-dkms-2.11.0-1.el7.src.rpm

  delegate_to: sugarsnax
  when: local_file.stat.exists == false and  remote_file.stat.exists == false

- name: fetch lustre client from build server
  fetch:
    src: /root/rpmbuild/RPMS/noarch/lustre-client-dkms-2.11.0-1.el7.centos.noarch.rpm
    dest: /tmp
  become: true
  delegate_to: sugarsnax
  when: local_file.stat.exists == false

- name: copy the lustre client to the remote machine
  copy:
    src: "{{ local_file.stat.path }}"
    dest: /tmp

- name: install lustre client
  yum:
    name: lustre-client-2.10.4-1.el7.x86_64
    state: present
    update_cache: yes
  become: true
