---
- name: Set /etc/hosts
  template:
    src: templates/hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true

- name: Set hostname to inventory_hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: make endpoints to mount isilon storage on.
  file:
    path: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - /apps
    - /.envsync/umcgst10/apps
    - /home

- name: install lustre client
  yum:
    name: lustre-client-2.10.4-1.el7.x86_64
    state: present
    update_cache: yes
  become: true

- name: Mount isilon apps
  mount:
    path: /apps
    src: gcc-storage001.stor.hpc.local:/ifs/rekencluster/umcgst10/apps
    fstype: nfs
    opts: defaults,_netdev,nolock,vers=4.0,noatime,nodiratime
    state: present

- name: Mount isilon home
  mount:
    path: /home
    src: gcc-storage001.stor.hpc.local:/ifs/rekencluster/umcgst10/home
    fstype: nfs
    opts: defaults,_netdev,nolock,vers=4.0,noatime,nodiratime
    state: present

- name: check if the lustre client is present locally
  stat:
    path: /tmp/sugarsnax/root/rpmbuild/RPMS/noarch/lustre-client-dkms-2.11.0-1.el7.centos.noarch.rpm
  register: local_file
  delegate_to: localhost

- name: Mount dh1
  mount:
    path: /mnt/dh1/groups
    src: 172.23.57.201@tcp11:172.23.57.202@tcp11:/dh1/groups
    fstype: lustre
    opts: rw,seclabel,lazystatfs
    state: present

- name: Mount dh2
  mount:
    path: /mnt/dh2/groups
    src: 172.23.57.203@tcp12:172.23.57.204@tcp12:/dh2/groups
    fstype: lustre
    opts: rw,seclabel,lazystatfs
    state: present

- name: install lustre client
  yum:
    name: lustre-client-2.10.4-1.el7.x86_64
    state: present
    update_cache: yes

- name: set lustre.conf
  template:
    src: templates/lustre.conf
    dest: /etc/modprobe.d/lustre.conf
    mode: 0644
    owner: root
    group: root
    backup: no

- name: mount all mountpoints in fstab
  command: mount -a
  args:
    warn: false
