---
- name: Set /etc/hosts
  template:
    src: templates/hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: true

- name: Set hostname to inventory_hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Create an ext4 filesystem on /dev/vdb
  filesystem:
    fstype: ext4
    dev: /dev/vdb

- name: Make scratch mountpoint
  file:
    path: "/scratch"
    mode: 0777
    state: directory

- name: Mount /dev/vdb on /scratch
  mount:
    path: /scratch
    src: /dev/vdb
    fstype: ext4
    opts: rw,relatime
    state: present
