---
- name: 'Gather facts from servers in "sys_admin_interface" group.'
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['sys_admin_interface'] }}"

- name: 'Include Slurm defaults from "slurm_management" role.'
  include_vars:
    file: '../../slurm_management/defaults/main.yml'
    name: 'slurm'

- name: 'Add Slurm group.'
  group:
    name: 'slurm'
    gid: "{{ slurm['slurm_gid'] }}"
  notify:
    - 'restart_slurmd'
  become: true

- name: 'Add Munge group.'
  group:
    name: 'munge'
    gid: "{{ slurm['munge_gid'] }}"
  notify:
    - 'restart_munge'
    - 'restart_slurmd'
  become: true

- name: 'Add Slurm user.'
  user:
    name: 'slurm'
    uid: "{{ slurm['slurm_uid'] }}"
    group: 'slurm'
  notify:
    - 'restart_slurmd'
  become: true

- name: 'Add Munge user.'
  user:
    name: 'munge'
    uid: "{{ slurm['munge_uid'] }}"
    group: 'munge'
  notify:
    - 'restart_munge'
    - 'restart_slurmd'
  become: true

- name: 'Install the Slurm client with yum.'
  yum:
    state: 'installed'
    update_cache: true
    allow_downgrade: true
    name:
      - "slurm*{{ slurm_version }}"
      - "slurm-slurmd*{{ slurm_version }}"
  notify:
    - 'restart_munge'
    - 'restart_slurmd'
  become: true

# See: https://bugs.schedmd.com/show_bug.cgi?id=8388
- name: 'Patch slurm daemon systemd service files to disable PID files.'
  lineinfile:
    path: "/usr/lib/systemd/system/{{ item }}.service"
    regexp: '^#?PIDFile='
    line: "#PIDFile=/var/run/slurm/{{ item }}.pid"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 'slurmd'
  notify:
    - 'restart_slurmd'
  become: true

- name: 'Install NHC with yum.'
  yum:
    state: 'latest'
    update_cache: true
    name:
      - 'lbnl-nhc'
  notify:
    - 'restart_slurmd'
  become: true

- name: 'Install munge_keyfile.'
  copy:
    src: "roles/slurm_management/files/{{ slurm_cluster_name }}_munge.key"
    owner: 'munge'
    group: 'munge'
    mode: '0600'
    dest: '/etc/munge/munge.key'
  notify:
    - 'restart_munge'
    - 'restart_slurmd'
  become: true

- name: 'Create folders for Slurm and NHC.'
  file:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: 'directory'
  with_items:
    - name: '/etc/slurm'
      owner: 'root'
      group: 'root'
      mode: '0755'
    - name: '/etc/nhc'
      owner: 'root'
      group: 'root'
      mode: '0755'
    - name: '/var/log/slurm'
      owner: 'slurm'
      group: 'root'
      mode: '0750'
    - name: '/var/spool/slurm'
      owner: 'slurm'
      group: 'root'
      mode: '0750'
    - name: '/var/spool/slurmd'
      owner: 'root'
      group: 'root'
      mode: '0755'
    - name: '/var/run/slurm'
      owner: 'slurm'
      group: 'root'
      mode: '0775'
  become: true

- name: 'Deploy slurm prolog/epilog scripts.'
  copy:
    src: "roles/slurm_management/files/{{ item }}"
    dest: '/etc/slurm/'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - 'slurm.prolog'
    - 'slurm.epilog'
    - 'slurm.taskprolog'
  become: true

- name: 'Deploy slurm.conf.'
  template:
    src: 'roles/slurm_management/templates/slurm.conf'
    dest: '/etc/slurm/slurm.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'restart_slurmd'
  become: true

- name: 'Configure cgroups.'
  copy:
    src: 'roles/slurm_management/files/cgroup.conf'
    dest: '/etc/slurm/cgroup.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'reload_slurmd'
  become: true

- name: 'Deploy UI nhc.conf.'
  template:
    src: 'templates/user_interface_nhc.conf'
    dest: '/etc/nhc/nhc.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: inventory_hostname in groups['user_interface']
  become: true

- name: 'Deploy compute_vm nhc.conf.'
  template:
    src: 'templates/compute_vm_nhc.conf'
    dest: '/etc/nhc/nhc.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: inventory_hostname in groups['compute_vm']
  become: true

- name: 'Start slurm and munge services.'
  systemd:
    name: "{{ item }}"
    enabled: 'yes'
    state: 'started'
    daemon_reload: 'yes'
  with_items:
    - 'munge.service'
    - 'slurmd.service'
  become: true

- name: 'Allow passwordless sudo to slurm user for users in the functional_admins_group.'
  template:
    src: 'roles/slurm_management/templates/91-slurm'
    dest: "/etc/sudoers.d/91-slurm"
    owner: 'root'
    group: 'root'
    mode: '0440'
  when: functional_admin_group is defined and functional_admin_group | length >= 1
  become: true
...
