---
- name: 'Create cron job to restart systemd-logind regularly as workaround for known DBus bug.'
  cron:
    #
    # Silly workaround for bug in interaction dbus <-> logind
    # Need DBus 1.11.10 for a fix, but CentOS 7.6 is stuck on dbus 1.10.24.
    #
    name: 'Restart systemd-logind'
    minute: '*/10'
    user: root
    job: '/bin/systemctl restart systemd-logind'
    cron_file: restart_logind
  become: true

- name: 'Install yum dependencies.'
  yum:
    state: 'latest'
    update_cache: true
    name:
      - pam_script
      - oddjob-mkhomedir
  notify:
    - authconfig_update
    - restart_oddjobd
  become: true

- name: 'Deploy password-auth-ac for PAM.'
  copy:
    src: 'password-auth-ac'
    dest: '/etc/pam.d/password-auth-ac'
    owner: root
    group: root
    mode: '0600'
  notify:
    - authconfig_update
    - restart_oddjobd
  become: true

- name: 'Enable pam_script.'
  file:  # noqa risky-file-permissions
    src: 'pam_script'
    dest: "/etc/{{ item }}"
    state: link
  with_items:
    - pam_script_acct
    - pam_script_auth
    - pam_script_passwd
    - pam_script_ses_close
    - pam_script_ses_open
  become: true

- name: 'Create /etc/pam-script.d/ dir.'
  file:
    name: '/etc/pam-script.d'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

#
# Login checks currently disabled,
# because error handling/reporting no longer works on CentOS >= 7.x,
# due to changes in the PAM stack.
# Login checks were only used to create Slurm accounts in the Slurm accounting DB.
# This functionality has been relocated to the Slurm job_submit.lua plugin,
# which will now automatically create account, users and associations of slurm users to slurm accounts
# upon job submission when they do not already exist.
#
# - name: Install login_checks.sh script.
#   copy:
#     src: 'login_checks.sh'
#     dest: '/etc/pam-script.d/login_checks.sh'
#     owner: root
#     group: root
#     mode: '0755'
#   when: inventory_hostname in groups['cluster']
#   become: true
#
# - name: Enable login_checks.sh script for ses_open.
#   file:  # noqa risky-file-permissions
#     src: "{{ item }}"
#     dest: "/etc/pam-script.d/{{ item }}_ses_open"
#     owner: root
#     group: root
#     state: link
#   with_items:
#     - login_checks.sh
#   when: inventory_hostname in groups['cluster']
#   become: true
#
- name: 'Disable login_checks.sh script as we use the Slurm job_submit.lua plugin now.'
  file:
    path: "/etc/pam-script.d/{{ item }}"
    state: absent
  with_items:
    - login_checks.sh_ses_open
    - login_checks.sh
  become: true

- name: 'Set tiny quota for regular users on jumphosts.'
  include_tasks:
    file: jumphost-quota.yml
  when:
    - inventory_hostname in groups['jumphost'] | default([])

- name: 'Enable services.'
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  with_items:
    - dbus.service
    - oddjobd.service
  notify:
    - authconfig_update
    - restart_oddjobd
  become: true
...
