#
# Create vxlans, routers and security groups.
#
---
- name: Create network.
  ansible.builtin.include_tasks:
    file: networks.yml
  loop: "{{ stack_networks
            | rejectattr('create', 'undefined')
            | selectattr('create', 'equalto', true)}}"
  loop_control:
    loop_var: network

- name: Create security groups.
  ansible.builtin.include_tasks:
    file: security_groups.yml
...
