---
- name: "Create {{ network['name'] }} network."
  openstack.cloud.network:
    state: present
    name: "{{ network['name'] }}"
    external: false  # This means we create the network ourselves here and it was not pre-defined outside OpenStack.
    mtu_size: "{{ network['mtu_size'] | default(omit) }}"
    wait: true
    timeout: "{{ openstack_api_timeout }}"

- name: "Assign subnet without gateway to closed {{ network['name'] }} network."
  openstack.cloud.subnet:
    # 'name' must be the same as 'network_name' or else creating routers for this subnet will fail due to known bug.
    name: "{{ network['name'] }}"
    network_name: "{{ network['name'] }}"
    state: present
    cidr: "{{ network['cidr'] }}"
    no_gateway_ip: true
    enable_dhcp: true
    dns_nameservers: "{{ nameservers }}"
    wait: true
    timeout: "{{ openstack_api_timeout }}"
  when: network['router'] is not defined

- name: "Assign subnet with gateway to {{ network['name'] }} network."
  openstack.cloud.subnet:
    # 'name' must be the same as 'network_name' or else creating routers for this subnet will fail due to known bug.
    name: "{{ network['name'] }}"
    network_name: "{{ network['name'] }}"
    state: present
    cidr: "{{ network['cidr'] }}"
    gateway_ip: "{{ network['router']['next-hop-address'] }}"
    enable_dhcp: true
    dns_nameservers: "{{ nameservers }}"
    wait: true
    timeout: "{{ openstack_api_timeout }}"
  when: network['router'] is defined

- name: "Create router to bridge {{ network['router']['external_network'] | default('---') }} and {{ network['name'] }} networks."
  openstack.cloud.router:
    state: present
    name: "Router bridging {{ network['router']['external_network'] }} and {{ network['name'] }}"
    network: "{{ network['router']['external_network'] }}"
    interfaces:
      # - "{{ network['name'] }}"
      #
      # Specifying only the network['name'] will fail when the default gateway / next-hop IP address
      # from that subnet is already in use. In that case we must specify an IP address,
      # but there is no easy, safe way to determine which one we should use....
      #
      - net: "{{ network['name'] }}"
        subnet: "{{ network['name'] }}"
        portip: "{{ network['router']['next-hop-address'] }}"
    wait: true
    timeout: "{{ openstack_api_timeout }}"
  when: network['router'] is defined
...
