---
- name: 'Install sysctl config file to manage coredumps upon next reboot.'
  template:
    src: 'templates/50-ansible-managed-coredumps.conf'
    dest: '/etc/sysctl.d/50-ansible-managed-coredumps.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true

- name: 'Modify sysctl kernel parameter to manage coredumps right now.'
  sysctl:
    name: kernel.core_pattern
    value: "{{ coredumps_pattern }}"
    sysctl_set: true
  become: true
...
